import type { Metadata } from "next";
import { Share_Tech_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/next"
import "./globals.css";



const shareTechMono = Share_Tech_Mono({
  weight: "400",  
  variable: "--font-share-tech-mono",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${shareTechMono.variable} antialiased`}
      >
        <Analytics/>
        {children}
      </body>
    </html>
  );
}
